require("dotenv").config({ path: "../../.env" });
const mongoose = require("mongoose");
const Menu = require("../models/Menu");
const connectDB = require("../config/database");

const menuData = [
  {
    name: "Chicken Biryani",
    description: "Aromatic basmati rice cooked with tender chicken and exotic spices",
    category: "Pakistani",
    ingredients: "Rice, Chicken, Saffron, Yogurt, Spices",
    calories: "450 kcal",
    price: 18,
    rating: 4.9,
    available: true,
    image: "https://images.unsplash.com/photo-1701579231349-d7459c40919d?w=800",
    featured: true,
    preparationTime: "30-40 mins",
  },
  {
    name: "Mutton Karahi",
    description: "Traditional Pakistani curry with tender mutton and fresh tomatoes",
    category: "Pakistani",
    ingredients: "Mutton, Tomatoes, Ginger, Garlic, Green Chilies",
    calories: "520 kcal",
    price: 25,
    rating: 4.8,
    available: true,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800",
    featured: false,
    preparationTime: "45-50 mins",
  },
  {
    name: "Seekh Kabab",
    description: "Minced meat kababs grilled to perfection with aromatic spices",
    category: "Pakistani",
    ingredients: "Minced Beef, Onions, Herbs, Spices",
    calories: "380 kcal",
    price: 15,
    rating: 4.7,
    available: true,
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800",
    featured: false,
    preparationTime: "20-25 mins",
  },
  {
    name: "Chicken Tikka",
    description: "Marinated chicken pieces grilled in tandoor",
    category: "Pakistani",
    ingredients: "Chicken, Yogurt, Tikka Masala, Spices",
    calories: "340 kcal",
    price: 16,
    rating: 4.8,
    available: true,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800",
    featured: false,
    preparationTime: "25-30 mins",
  },
  {
    name: "Chicken Chow Mein",
    description: "Stir-fried noodles with chicken and fresh vegetables",
    category: "Chinese",
    ingredients: "Noodles, Chicken, Vegetables, Soy Sauce",
    calories: "420 kcal",
    price: 16,
    rating: 4.6,
    available: true,
    image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=800",
    featured: true,
    preparationTime: "15-20 mins",
  },
  {
    name: "Sweet & Sour Chicken",
    description: "Crispy chicken tossed in tangy sweet and sour sauce",
    category: "Chinese",
    ingredients: "Chicken, Bell Peppers, Pineapple, Sweet & Sour Sauce",
    calories: "480 kcal",
    price: 18,
    rating: 4.5,
    available: true,
    image: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800",
    featured: false,
    preparationTime: "20-25 mins",
  },
  {
    name: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts and vegetables",
    category: "Chinese",
    ingredients: "Chicken, Peanuts, Vegetables, Chili Peppers",
    calories: "410 kcal",
    price: 17,
    rating: 4.7,
    available: true,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800",
    featured: false,
    preparationTime: "18-22 mins",
  },
  {
    name: "Spring Rolls",
    description: "Crispy fried rolls filled with vegetables",
    category: "Chinese",
    ingredients: "Wrapper, Cabbage, Carrots, Soy Sauce",
    calories: "280 kcal",
    price: 9,
    rating: 4.4,
    available: true,
    image: "https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=800",
    featured: false,
    preparationTime: "15-18 mins",
  },
  {
    name: "Spaghetti Carbonara",
    description: "Classic Italian pasta with creamy sauce and crispy bacon",
    category: "Italian",
    ingredients: "Spaghetti, Eggs, Bacon, Parmesan, Black Pepper",
    calories: "550 kcal",
    price: 20,
    rating: 4.8,
    available: true,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
    featured: true,
    preparationTime: "20-25 mins",
  },
  {
    name: "Margherita Pizza",
    description: "Wood-fired pizza with fresh mozzarella and basil",
    category: "Italian",
    ingredients: "Dough, Tomato Sauce, Mozzarella, Basil, Olive Oil",
    calories: "620 kcal",
    price: 22,
    rating: 4.9,
    available: true,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    featured: true,
    preparationTime: "25-30 mins",
  },
  {
    name: "Fettuccine Alfredo",
    description: "Creamy pasta with parmesan cheese and butter",
    category: "Italian",
    ingredients: "Fettuccine, Cream, Butter, Parmesan, Garlic",
    calories: "580 kcal",
    price: 21,
    rating: 4.7,
    available: false,
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800",
    featured: false,
    preparationTime: "20-25 mins",
  },
  {
    name: "BBQ Platter",
    description: "Mixed grill platter with chicken, beef, and lamb",
    category: "BBQ",
    ingredients: "Chicken, Beef, Lamb, BBQ Sauce, Spices",
    calories: "680 kcal",
    price: 32,
    rating: 5.0,
    available: true,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
    featured: true,
    preparationTime: "35-40 mins",
  },
  {
    name: "Beef Ribs",
    description: "Slow-cooked beef ribs with smoky BBQ sauce",
    category: "BBQ",
    ingredients: "Beef Ribs, BBQ Sauce, Brown Sugar, Spices",
    calories: "720 kcal",
    price: 28,
    rating: 4.8,
    available: true,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
    featured: false,
    preparationTime: "40-45 mins",
  },
  {
    name: "Grilled Chicken Wings",
    description: "Juicy chicken wings grilled with special marinade",
    category: "BBQ",
    ingredients: "Chicken Wings, Honey, Garlic, Soy Sauce",
    calories: "380 kcal",
    price: 15,
    rating: 4.6,
    available: true,
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800",
    featured: false,
    preparationTime: "20-25 mins",
  },
  {
    name: "Beef Steak",
    description: "Premium cut beef steak grilled to perfection",
    category: "BBQ",
    ingredients: "Beef Tenderloin, Garlic Butter, Herbs",
    calories: "650 kcal",
    price: 35,
    rating: 5.0,
    available: true,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800",
    featured: true,
    preparationTime: "30-35 mins",
  },
  {
    name: "Classic Burger",
    description: "Juicy beef patty with cheese, lettuce, and special sauce",
    category: "Fast Food",
    ingredients: "Beef Patty, Cheese, Lettuce, Tomato, Sauce",
    calories: "520 kcal",
    price: 12,
    rating: 4.5,
    available: true,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    featured: false,
    preparationTime: "10-15 mins",
  },
  {
    name: "Loaded Fries",
    description: "Crispy fries topped with cheese, bacon, and jalapeños",
    category: "Fast Food",
    ingredients: "Fries, Cheese, Bacon, Jalapeños, Sour Cream",
    calories: "580 kcal",
    price: 10,
    rating: 4.7,
    available: true,
    image: "https://images.unsplash.com/photo-1630431341973-02e1a5f4e11f?w=800",
    featured: false,
    preparationTime: "12-15 mins",
  },
  {
    name: "Crispy Chicken Sandwich",
    description: "Breaded chicken with coleslaw and spicy mayo",
    category: "Fast Food",
    ingredients: "Chicken Breast, Bun, Coleslaw, Spicy Mayo",
    calories: "490 kcal",
    price: 13,
    rating: 4.6,
    available: true,
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800",
    featured: false,
    preparationTime: "12-15 mins",
  },
  {
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center",
    category: "Dessert",
    ingredients: "Chocolate, Eggs, Butter, Flour, Sugar",
    calories: "420 kcal",
    price: 12,
    rating: 4.9,
    available: true,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
    featured: false,
    preparationTime: "15-18 mins",
  },
  {
    name: "Tiramisu",
    description: "Classic Italian dessert with coffee and mascarpone",
    category: "Dessert",
    ingredients: "Ladyfingers, Coffee, Mascarpone, Cocoa",
    calories: "380 kcal",
    price: 11,
    rating: 4.8,
    available: true,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
    featured: false,
    preparationTime: "10-12 mins",
  },
  {
    name: "New York Cheesecake",
    description: "Creamy cheesecake with graham cracker crust",
    category: "Dessert",
    ingredients: "Cream Cheese, Eggs, Sugar, Graham Crackers",
    calories: "450 kcal",
    price: 13,
    rating: 4.7,
    available: true,
    image: "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=800",
    featured: false,
    preparationTime: "12-15 mins",
  },
  {
    name: "Fresh Mango Smoothie",
    description: "Refreshing smoothie with fresh mangoes and yogurt",
    category: "Drinks",
    ingredients: "Mango, Yogurt, Milk, Honey",
    calories: "220 kcal",
    price: 8,
    rating: 4.8,
    available: true,
    image: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800",
    featured: false,
    preparationTime: "5-7 mins",
  },
  {
    name: "Mint Mojito",
    description: "Refreshing mocktail with mint and lime",
    category: "Drinks",
    ingredients: "Mint, Lime, Sugar, Soda Water",
    calories: "120 kcal",
    price: 7,
    rating: 4.6,
    available: true,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800",
    featured: false,
    preparationTime: "5-7 mins",
  },
  {
    name: "Iced Coffee",
    description: "Cold brew coffee with milk and vanilla",
    category: "Drinks",
    ingredients: "Coffee, Milk, Vanilla, Ice",
    calories: "150 kcal",
    price: 6,
    rating: 4.5,
    available: true,
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800",
    featured: false,
    preparationTime: "5 mins",
  },
];

const seedMenus = async () => {
  try {
    await connectDB();

    // Clear existing data
    await Menu.deleteMany();
    console.log("✅ Existing menu data cleared");

    // Insert new data
    const menus = await Menu.insertMany(menuData);
    console.log(`✅ ${menus.length} menu items added successfully`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding menu data:", error);
    process.exit(1);
  }
};

seedMenus();
